### ISSUE TITLE
wrong calculation of overrun?

### ISSUE THREAD

**Issue by kwrtz** [arkhipenko/TaskScheduler#104]
```
				iCurrent->iPreviousMillis += iCurrent->iDelay;

#ifdef _TASK_TIMECRITICAL
				// Updated_previous+current interval should put us into the future, so iOverrun should be positive or zero.
				// If negative - the task is behind (next execution time is already in the past)
				unsigned long p = iCurrent->iPreviousMillis;
				iCurrent->iOverrun = (long)(p + i - m);
```

In the first line you calculate the future when the task should run again.
In iOverrun you add the interval again. Is that correct? Because now you have two times delay added.

**Comment by arkhipenko** [comment]
It might be a bit confusing but is correct. 
iPreviousMillis is always a point in time of the last start.
So iPrevious + iDelay should be right after or equal to now, and another interval should put you in the future. 
If that next interval does not put you in the future, you know you are in the overrun situation.
