### ISSUE TITLE
compiler warning

### ISSUE THREAD

**Issue by olonsoft** [arkhipenko/TaskScheduler#111]
Not an issue but just a warning:
Using platformio with vscode I get 
```ISO C++17 does not allow 'register' storage class```
at file TackScheduler.h line 981
```register unsigned long m, i;  // millis, interval;```

**Comment by arkhipenko** [comment]
Did some reading and it seems it was already "only a hint" for some time. Will get rid of it in the later versions. Thanks.

**Comment by arkhipenko** [comment]
Pushed to testing branch
