### ISSUE TITLE
Exception 28 when calling millis() from Scheduler::execute()

### ISSUE THREAD

**Issue by yashodeepk** [arkhipenko/TaskScheduler#116]
I have the lastest version of TaskScheduler

I am getting this Exception randomly

Exception 28: LoadProhibited: A load referenced a page mapped with an attribute that does not permit loads
PC: 0x40101c77
EXCVADDR: 0x00008014

Decoding stack results
0x401002ec: millis() at C:\Users\HP\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_wiring.cpp line 185
0x40100224: ets_post(uint8, ETSSignal, ETSParam) at C:\Users\HP\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 177
0x4020bd5a: Scheduler::execute() at C:\Users\HP\Documents\Arduino\libraries\TaskScheduler\src/TaskScheduler.h line 1035
0x40202ae2: loop() at C:\Users\HP\Documents\Arduino\libraries\Painless_Mesh\src/arduino/wifi.hpp line 191
0x40100224: ets_post(uint8, ETSSignal, ETSParam) at C:\Users\HP\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 177
0x40100245: esp_schedule() at C:\Users\HP\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 125
0x40216c8c: loop_wrapper() at C:\Users\HP\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 197

Need a help here

**Comment by arkhipenko** [comment]
Need to see your code to be able to help.
