### ISSUE TITLE
about delay() in libs.

### ISSUE THREAD

**Issue by youxiaojie** [arkhipenko/TaskScheduler#123]
dear sir,
I hope multitask in arduino, I read a lot of articles which mentioned "forget delay() in multi task".
but I see lots of libs using delay(), should I rewrite these libs?

**Comment by arkhipenko** [comment]
Yes, and I have written a guide about it:

https://github.com/arkhipenko/TaskScheduler/wiki/Creating TaskScheduler friendly libraries
