### ISSUE TITLE
Multiple Thread and Multiple Core in ESP32?

### ISSUE THREAD

**Issue by sseodate** [arkhipenko/TaskScheduler#125]
I couldnt find a way to assign task to core 0  in ESP32 , could i do that with this lib ?

**Comment by arkhipenko** [comment]
No. 
Red the docu:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/freertos-smp.html

**Comment by sseodate** [comment]
Tks alot man!
