### ISSUE TITLE
Compiler warning: 'uint32_t _task_micros()'  defined but not used

### ISSUE THREAD

**Issue by numericOverflow** [arkhipenko/TaskScheduler#133]
When using this library using Visual Studio Code, the compiler throws a warning about one of the functions:

`Compiling .pio\build\nodemcuv2\src\main.master.cpp.o
In file included from src\main.master.cpp:117:
.pio\libdeps\nodemcuv2\TaskScheduler\src/TaskScheduler.h:280:17: warning: 'uint32_t _task_micros()' 
defined but not used [-Wunused-function]
280 | static uint32_t _task_micros() {return micros();}
      |                 ^~~~~~~~~~~~`

![2021-12-31_112549](https://user-images.githubusercontent.com/3429424/147833964-75e41e64-d637-43d3-9f0e-e1ce81f24332.jpg)

It looks like there's a [PR to fix](https://github.com/arkhipenko/TaskScheduler/pull/129), can you look into fixing this issue?

I'm using the latest TaskScheduler lib version as of today (v3.6.0)

**Comment by andriy063** [comment]
The same issue

**Comment by abrahmx** [comment]
Same issue here 
![image](https://user-images.githubusercontent.com/13279232/221294549-298891f4-8cf5-4880-8f3e-ef4626205226.png)

**Comment by arkhipenko** [comment]
This is fixed as of 3.8.2

**Comment by lexskal** [comment]
// ------------------ TaskScheduler implementation --------------------

#ifndef _TASK_EXTERNAL_TIME
static uint32_t _task_millis() {return millis();}
//static uint32_t _task_micros() {return micros();}
#endif  //  _TASK_EXTERNAL_TIME
