### ISSUE TITLE
Conflict with AsyncHTTPSRequest_Generic

### ISSUE THREAD

**Issue by DavidAntonin** [arkhipenko/TaskScheduler#134]
I found a problem when using the TaskScheduler and
AsyncHTTPSRequest_Generic. If I activate TS, responses to requests from AsyncHTTPSRequest_Generic come significantly later than without TS. 
I even figured out that if TS is active, it blocks the proper function of receiving 433MHz signal via RCswitch. TS seems to interfere with the timing function of other libraries
Arduino IDE 1.8.19
ESP32 DOIT DEV KIT1 - arduino library 2.0.2

**Comment by arkhipenko** [comment]
I need to see the code in order to understand what the problem is.

**Comment by m-maazi** [comment]
Yes I have same issue.

**Comment by arkhipenko** [comment]
No worries! Glad it worked out.
