### ISSUE TITLE
Set the core where a task execute

### ISSUE THREAD

**Issue by sebarch** [arkhipenko/TaskScheduler#164]
Hi, it´s possible to set the core where a task is executed without using freertos? Thanks

**Comment by arkhipenko** [comment]
Hi.

No. TaskScheduler is a cooperative library, so it run in one thread in whatever task the scheduler and task objects are being called from. In fact, if you do use multiple rtos tasks, you should compile with thread protection.

Having said that, you can influence which core the rtos tasks is running on.
For example and inspiration, please check the main sketch of the repo below.

https://github.com/arkhipenko/dnd/blob/master/esp32_dnd_rtos_mjpeg_multi/esp32_dnd_rtos_mjpeg_multi.ino

The method you'd want to look closely at is
creareCoreTasks()

Notice how the video streaming task and TaskScheduler task are created pinned to different cores.
Works like a charm.

Hope this helps.

Cheers,
Anatoli


Sent from my mobile implant.
Apologies for autocorrect.
________________________________
From: sebarch ***@***.***>
Sent: Friday, April 21, 2023 8:35:50 PM
To: arkhipenko/TaskScheduler ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [arkhipenko/TaskScheduler] Set the core where a task execute (Issue #164)


Hi, it´s possible to set the core where a task is executed without using freertos? Thanks

**Comment by sebarch** [comment]
Thanks for your quick replay
