### ISSUE TITLE
Declare task to run with delay

### ISSUE THREAD

**Issue by vatsake** [arkhipenko/TaskScheduler#165]
Currently if I enable a task, it runs immediately. 
Can you enable it with delay? Without calling `<task>.enableDelayed();`

**Comment by arkhipenko** [comment]
Hi,
That's what task.enableDelayed() is there for. Why can't you use it?


You can also do:

task.enable();
task.delay() or task.delay(time);

this is actually what enableDelayed() is doing.



________________________________
From: vatsake ***@***.***>
Sent: Friday, April 28, 2023 7:16 AM
To: arkhipenko/TaskScheduler ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [arkhipenko/TaskScheduler] Declare task to run with delay (Issue #165)


Currently if I enable a task, it runs immediately.
Can you enable it with delay? Without calling <task>.enableDelayed();
