### ISSUE TITLE
Library Suggestion

### ISSUE THREAD

**Issue by georgevbsantiago** [arkhipenko/TaskScheduler#172]
Hello, @arkhipenko 

Your library is fantastic. Thank you for this important contribution.

I found another interesting library that deals with cooperative Multitasking. Apparently, the development of the project is stopped, but I'll leave the link here, because the code can have good ideas to implement in TaskScheduler.

[H4 library (linK)](https://github.com/philbowles/H4)
[H4 Plus library (link)](https://github.com/philbowles/h4plugins)

Thank you very much

**Comment by arkhipenko** [comment]
Thank you, @georgevbsantiago  - I will have a look.
