### ISSUE TITLE
ODR Violation With Multiple Uses of TaskScheduler Throughout a Project

### ISSUE THREAD

**Issue by tkw722** [arkhipenko/TaskScheduler#175]
Hello!

I've got a pretty simple problem that is leading to a pretty massive blocker. I'm including `TaskScheduler.h` in several places throughout my project as I have tasks in several different places throughout the project. The challenge I'm running into, is TaskScheduler seems to have been built with both declarations and definitions in the same `.h` file. This results in breaking the One Definition Rule when the compiler runs causing multiple definition warnings and a build failure. Have others seen this issue? Is there a way past this? I fully acknowledge that there could be something simple I'm just missing.

Thanks!

**Comment by arkhipenko** [comment]
Check examples 16 and/or 27.
