### ISSUE TITLE
License slightly cumbersome

### ISSUE THREAD

**Issue by matthijskooijman** [arkhipenko/TaskScheduler#21]
This project currently uses an older version of the BSD license (AFAICS). It is fairly liberal, but contains two clauses that are a bit cumbersome for our project:
 1. "Redistribution and use in source and binary forms are permitted provided that the above copyright notice and this paragraph are duplicated in all such forms", which means the full license text must be present in the binary, taking up flash space (it does not actually require displaying the text anywhere, but that would of course make sense).
 2. "and that any documentation, advertising materials, and other materials related to such distribution and use acknowledge that the software was developed by Anatoli Arkhipenko", which means we should be mentioning your name pretty much everywhere.

I suspect that neither of these are actually your intention? If they are indeed not, perhaps the 3-clause BSD license would be a better fit: https://opensource.org/licenses/BSD-3-Clause It still requires keeping the license and copyright in source versions, but only requires them to be present in any documentation accompanying the binary version.

I would be grateful if you could consider this request swiftly, since we are planning to make a release of our software soon.

**Comment by arkhipenko** [comment]
Hi,
Sorry for the delay. I am fine with the update. 
Changed the license already. 

Cheers.
