### ISSUE TITLE
Add to platformio regristry

### ISSUE THREAD

**Issue by zhakhalov** [arkhipenko/TaskScheduler#24]
Hi,
I'm using platformio for my projects.
It is really great library, and I would like to have this library as external dependenty.
Please add this library to platformio registry.

Here is link to instructions.
http://docs.platformio.org/en/latest/librarymanager/creating.html#at-github

Thanks in advance

**Comment by arkhipenko** [comment]
Thanks. Just did it. As soon as it passes the moderators, it will be available.
