### ISSUE TITLE
Blocking tasks request

### ISSUE THREAD

**Issue by syproduction** [arkhipenko/TaskScheduler#35]
Hi!
Can I do a program executing one task after another? For example, create a task to execute for a particular time and other tasks are waiting?

**Comment by arkhipenko** [comment]
Of course!
Just enable the next task in the OnDisable method of the previous.



Sent from a mobile device. Apologies for accidental typos.


-------- Original message --------

**Comment by arkhipenko** [comment]
The other way is to use StatusRequest objects and trigger subsequent task execution when the appropriate task finishes. StatusRequest objects are described in the docu and there are a couple of examples with them. Also, my latest IoT_APIS project uses them a lot to coordinate readings from multiple sensors -  feel free to have a look!
