### ISSUE TITLE
Stable State for an task

### ISSUE THREAD

**Issue by Jomelo** [arkhipenko/TaskScheduler#44]
Hello, 
it is possible to set a task in a stable state when the status is changed to disable ?

For example: a pump control task

first iteration:
  // init something

loop:
 // ....

stable stop/disable state:
 //  pump stop

**Comment by arkhipenko** [comment]
Yes, this is what OnEnable and OnDisable methods are for.
Please refer to [wiki-page](https://github.com/arkhipenko/TaskScheduler/wiki/API-Task#taskunsigned-long-ainterval-long-aiterations-void-acallback-scheduler-ascheduler-bool-aenable-bool-aonenable-void-aondisable)

**Comment by arkhipenko** [comment]
Also, an example of use: [APIS code for watering](https://github.com/arkhipenko/apis/blob/master/apis.ino#L637)
