### ISSUE TITLE
porting to ESP32?

### ISSUE THREAD

**Issue by baggior** [arkhipenko/TaskScheduler#46]
what about porting to ESP32?

beside all defines is needed to remove the dependecy to 
#include "user_interface.h"

**Comment by arkhipenko** [comment]
Definitely in the plan, and I even have the ESP32 chip at home, just not the time to actually do it.
Could you create a PR?

**Comment by arkhipenko** [comment]
Pushed v2.6.0 into the "testing" branch with ESP32 support. Could you please test?
https://github.com/arkhipenko/TaskScheduler/tree/testing

**Comment by arkhipenko** [comment]
Updated "testing" with recent changes. Please test.
