### ISSUE TITLE
Question on Time Critical

### ISSUE THREAD

**Issue by wmarchewka** [arkhipenko/TaskScheduler#49]
Great library! Makes my code so modular.  But i have a question on Time Critical.  I am running Scheduler_example09_TimeCritical  and I have modified it by removing the random delay. But i still get start delayed showing up as 1 at random intervals, it is mostly 0, and never more than one. Would that be considered jitter? i am using a ESP8266.

**Comment by arkhipenko** [comment]
For time critical applications, could you please try running with  #define _TASK_SLEEP_ON_IDLE_RUN commented out?

**Comment by wmarchewka** [comment]
That fixed the issue. Thank you.
