### ISSUE TITLE
Warning, Category

### ISSUE THREAD

**Issue by Markolise** [arkhipenko/TaskScheduler#5]
Not really a big issue, but getting this warning **"WARNING: Category 'Schedulers' in Library TaskScheduler is not valid. Setting to 'Uncategorized'"**
Any idea how to fix that, or is there something I need to modify in the arduino settings to make that category valid?

**Comment by arkhipenko** [comment]
There is no appropriate category for TaskScheduler in the Arduino IDE library manager. I will ask the developers. Please ignore this warning, it does not affect functionality whatsoever.




On Mon, Nov 2, 2015 at 4:18 PM -0800, "Markolise" <notifications@github.com> wrote:
Not really a big issue, but getting this warning "WARNING: Category 'Schedulers' in Library TaskScheduler is not valid. Setting to 'Uncategorized'"
Any idea how to fix that, or is there something I need to modify in the arduino settings to make that category valid?

---
Reply to this email directly or view it on GitHub:
https://github.com/arkhipenko/TaskScheduler/issues/5

**Comment by arkhipenko** [comment]
Below is a list of library categories currently supported by IDE:

Display
Communication
Signal Input/Output
Sensors
Device Control
Timing
Data Storage
Data Processing
Other
Uncategorized

don't see TaskScheduler fitting into any of them cleanly. Perhaps I should make it "Timing", or "Device Control", or "Other"?

**Comment by Hannes-III** [comment]
I vote for Timing! That's how I found your Library in the first place.

**Comment by arkhipenko** [comment]
Timing it is then. Updated library.properties file.
