### ISSUE TITLE
Document approximate memory requirements

### ISSUE THREAD

**Issue by hattesen** [arkhipenko/TaskScheduler#55]
It would be really nice to know the approximate memory (program and RAM) requirements for this library with the various compile parameters enabled. Any chance of getting that into the documentation (WiKi)?

**Comment by arkhipenko** [comment]
Memory requirements: 46 bytes (plain vanilla), 57 bytes (IDLE sleep, WDT and LTS pointer support). Other options have similar memory footprints. 

Wiki updated
