### ISSUE TITLE
Doesnt work if use function => while (Client.connected())

### ISSUE THREAD

**Issue by adamrabbani** [arkhipenko/TaskScheduler#59]
i use this function => while (Client.connected()) for client-server communication..
when esp run the function.. other function delayed until client connected to the server

**Comment by GitMoDu** [comment]
A **cooperative** Sheduler will not yield execution if you don't exit it. You're thinking about a **preemptive** scheduler, like FreeRTOS.

**Comment by adamrabbani** [comment]
Oh, Thanks!
