### ISSUE TITLE
Compatibility Issue with arduino-1.6.6

### ISSUE THREAD

**Issue by alinleonard** [arkhipenko/TaskScheduler#6]
First example run:
```
 error: 't1Callback' was not declared in this scope
```

**Comment by arkhipenko** [comment]
About to release v1.8.3 which will fix the issue. In the meantime you can just declare all callback functions as function prototypes [  void function();   ] at the beginning of the sketch, and that would fix the issue.




On Fri, Nov 13, 2015 at 10:39 AM -0800, "alinleonard" <notifications@github.com> wrote:
First example run:
```
 error: 't1Callback' was not declared in this scope
```



---
Reply to this email directly or view it on GitHub:
https://github.com/arkhipenko/TaskScheduler/issues/6

**Comment by alinleonard** [comment]
yes I did that , just reported.

**Comment by arkhipenko** [comment]
Worth mentioning that this is a new issue introduced by Arduino v 1.6.6
If you continue using v 1.6.5 with avr <= 1.6.8 all existing sketches compile just fine.
