### ISSUE TITLE
OLED turn off after some time

### ISSUE THREAD

**Issue by tstanescu1** [arkhipenko/TaskScheduler#66]
Thank you for this great scheduler.. I've been able to do pretty much everything I've needed except one weird task.

I'm trying to set up a timeout on an OLED screen connected to the arduino. There is a button that can turn it off or on, but I'd like to implement a timeout after let's say 60 seconds to save the screen. 

I've set up all the tasks, and tried to use the t1.delay(60000); method but it didn't do anything, eg:

void displayWake() {
  
 u8x8.setPowerSave(false); //screen is on
 sleepTimerTask.setCallback(&displaySleep); //method sets power save to true
 sleepTimerTask.delay(60000); //delay before the function above is executed

}
 where the sleep timer is: Task sleepTimerTask(TASK_SECOND, TASK_ONCE, &displaySleep);

Thanks again for your help
T

**Comment by arkhipenko** [comment]
Each task can be assigned a timeout since version 2.6.0
What you need to do is:

``` c++
#define _TASK_TIMEOUT   
#include <TaskScheduler.h>
...
void displaySleep();

Scheduler ts;
Task sleepTimerTask(TASK_MINUTE, TASK_ONCE, &displaySleep, ts, false);

void displaySleep() {
// do whatever needs to be done to turn the OLED Off
}

void displayWake() { 
  u8x8.setPowerSave(false); //screen is on
  sleepTimerTask.restartDelayed(); //restart the timer function
}
```
If anywhere in the code you want to reset the timeout (i.e., a button is pressed):

```
if (buttonPin == HIGH) {
  // do button stuff
  sleepTimerTask.restartDelayed(); //restart the timer function
}
```

**Comment by tstanescu1** [comment]
Thanks so much for your reply. Unfortunately I can't seem to wrap my head around this timeout. I've tried several combinations and it doesn't seem like the displaySleep function is engaging, it doesn't sleep.  Do I need to enable anything else? What about using something like the following, where I could add one task after the other?

Task t2(5 * TASK_SECOND, TASK_FOREVER, &task2Callback, &ts, false, NULL, &task2OnDisable);

**Comment by tstanescu1** [comment]
Here is the code I have right now, it's quite messy sorry:
`//Temperature
#include <OneWire.h> //Used for temp
int DS18S20_Pin = 4; //DS18S20 Signal pin on digital 2
OneWire ds(DS18S20_Pin);  //Temperature chip i/o

//TDS Sensor
#define TdsSensorPin A1
#define VREF 5.0      // analog reference voltage(Volt) of the ADC
#define SCOUNT  30           // sum of sample point
int analogBuffer[SCOUNT];    // store the analog value in the array, read from ADC
int analogBufferTemp[SCOUNT];
int analogBufferIndex = 0, copyIndex = 0;
float averageVoltage = 0, tdsValue = 0;

//PH Sensor
#define SensorPin A0            //pH meter Analog output to Arduino Analog Input 0
#define Offset 0.00            //deviation compensate
#define samplingInterval 20
#define printInterval 800
#define ArrayLenth  40    //times of collection
int pHArray[ArrayLenth];   //Store the average value of the sensor feedback
int pHArrayIndex = 0;

/* Simple version of the wake up on capacitive button */
#include <U8x8lib.h> //Display library
#include <TaskScheduler.h>

//Capacitative Button
int pushButton = 11;

#define DISPLAY_AUTOSLEEP_MS 15000  // sleep display on idle (after ms)
#define DISPLAY_BLIT_FREQ 1000       // redraw display every second

// Forward declarations for Display
void blitDisplay(); //Function that draws the displays data on OLED, but no backlight here
void tick(); //Function that senses rotary click or movement to wake up screen
void displaySleep(); //Function that makes screen sleep
void displayWake(); //Function that wakes up screen

//void ph();

// logic variables
//int timelapseInterval = 0;
//bool timelapseRunning = false;
bool blit = true;

// Library initializations
U8X8_SH1106_128X64_NONAME_HW_I2C u8x8(/* reset=*/ U8X8_PIN_NONE);

Scheduler scheduler;
Task sleepTimerTask(TASK_SECOND * 10, TASK_ONCE, &displaySleep, &scheduler, false);
Task blitDisplayTask(DISPLAY_BLIT_FREQ, TASK_FOREVER, &blitDisplay);

//Task sensorDataSend(TASK_SECOND, TASK_FOREVER, &sensorRead);


void setup(void) {

  pinMode(pushButton, INPUT); //Capacitive touch sensor
  pinMode(TdsSensorPin, INPUT); //TDS/PPM Sensor
  u8x8.begin();
  //u8x8.setFont(u8x8_font_pxplusibmcgathin_r);
  u8x8.setFont(u8x8_font_chroma48medium8_r);
  u8x8.setContrast(0); //dims it down

  // Initialize the scheduler.
  scheduler.init();
  scheduler.addTask(blitDisplayTask);
//  scheduler.addTask(sleepTimerTask);
  //blitDisplayTask.enable();
  //sleepTimerTask.enable();
  scheduler.enableAll();
 // sleepTimerTask.setTimeout(10 * TASK_SECOND);
  

  


}

//#define iPH 0
//#define iTEMP 1
//#define iLIGHT1 2
//static float SENSOR_DATA[3] = { 0.0 , 20.0, 1};
////static String SENSOR_NAME[3] = { "PH", "Temp/C", "Light1" };
////static String SENSOR_SYMBOL[3] = { "PH", "TEMP", "L1" };
//
//static void getSensorData() {
//  float temp = getTemp(); 
//  //SENSOR_DATA[iPH] = getTemp();
//  //SENSOR_DATA[iLIGHT1] = getTemp();
//}



void loop(void) {
  //Sensors:
  ppm();
  tick();               // tick inputs
  scheduler.execute();  // tick scheduler

}

void blitDisplay() { //Function that displays on OLED

  if (blit) {   // blit must be on for screen to draw, but doesnt control backlight
    //ON / OFF ?
    //u8x8.drawString(13, 7, timelapseRunning ? "ON " : "OFF"); // X, Y, if timelapserunning TRUE? then
    u8x8.setInverseFont(1);
    u8x8.drawString(0, 0, "HydraPonics V0.2");

    
    //PH Display
    u8x8.setInverseFont(1);
    u8x8.drawString(0, 2, "pH Value:       ");
    u8x8.setInverseFont(0);
    u8x8.setCursor(0, 3);
    float pHValue = ph();
    u8x8.print(pHValue, 2);
    u8x8.drawString(5, 3, "pH");
    //u8x8.setCursor(9, 3);
    //u8x8.print(voltage,2);
    //u8x8.drawString(14, 3, "v");

    //PPM/EC Display
    u8x8.setInverseFont(1);
    u8x8.drawString(0, 4, "PPM/EC:         ");
    u8x8.setInverseFont(0);
    u8x8.setCursor(0, 5);
    u8x8.print(tdsValue, 0);
    u8x8.drawString(5, 5, "ppm");
    u8x8.setCursor(9, 5);
    u8x8.print(tdsValue * 2 / 1000);
    u8x8.drawString(14, 5, "EC");

    //Temp Display
    u8x8.setInverseFont(1);
    u8x8.drawString(0, 6, "Temperature:    ");
    // u8x8.setFont(u8x8_font_amstrad_cpc_extended_r);
    u8x8.setInverseFont(0);
    u8x8.setCursor(0, 7);
    float temperature = getTemp();
    //SENSOR_DATA[1];
    u8x8.print(temperature);
    u8x8.drawString(5, 7, "^C");
    u8x8.setCursor(8, 7);
    u8x8.print(temperature * 9 / 5 + 32);
    u8x8.drawString(13, 7, "^F");

    sleepTimerTask.enable();
  }
  blit = false; //drawing done, blitter off
}

void tick(void) { //Checks button, and rotary, and wakes up screen on click

  //CAPACITIVE TOUCH TO TURN SCREEN ON/OFF - SIMPLE BUT IN THE FUTURE SHOULD ALSO TIMEOUT AND MAKE PIN OFF
  int buttonState = digitalRead(pushButton);
  if (buttonState == HIGH) { //If button is clicked, device is not sleeping
    blit = true;
    displayWake();
  }
  else {
    displaySleep();
    blit = false;

  }

}

void displaySleep() {
  u8x8.setPowerSave(true);
  blit = false;
    Serial.print("Sleep");
}

void displayWake() {
  u8x8.setPowerSave(false);
  Serial.print("Awake");
}

double avergearray(int* arr, int number) { //PH Formula
  int i;
  int max, min;
  double avg;
  long amount = 0;
  if (number <= 0) {
    Serial.println("Error number for the array to avraging!/n");
    return 0;
  }
  if (number < 5) { //less than 5, calculated directly statistics
    for (i = 0; i < number; i++) {
      amount += arr[i];
    }
    avg = amount / number;
    return avg;
  } else {
    if (arr[0] < arr[1]) {
      min = arr[0]; max = arr[1];
    }
    else {
      min = arr[1]; max = arr[0];
    }
    for (i = 2; i < number; i++) {
      if (arr[i] < min) {
        amount += min;      //arr<min
        min = arr[i];
      } else {
        if (arr[i] > max) {
          amount += max;  //arr>max
          max = arr[i];
        } else {
          amount += arr[i]; //min<=arr<=max
        }
      }//if
    }//for
    avg = (double)amount / (number - 2);
  }//if
  return avg;
}

float ppm() { //PPM Formulas
  static unsigned long analogSampleTimepoint = millis();
  if (millis() - analogSampleTimepoint > 40U)  //every 40 milliseconds,read the analog value from the ADC
  {
    analogSampleTimepoint = millis();
    analogBuffer[analogBufferIndex] = analogRead(TdsSensorPin);    //read the analog value and store into the buffer
    analogBufferIndex++;
    if (analogBufferIndex == SCOUNT)
      analogBufferIndex = 0;
  }
  static unsigned long printTimepoint = millis();
  if (millis() - printTimepoint > 800U)
  {
    printTimepoint = millis();
    for (copyIndex = 0; copyIndex < SCOUNT; copyIndex++)
      analogBufferTemp[copyIndex] = analogBuffer[copyIndex];
    averageVoltage = getMedianNum(analogBufferTemp, SCOUNT) * (float)VREF / 1024.0; // read the analog value more stable by the median filtering algorithm, and convert to voltage value
    float temperature = getTemp();
    float compensationCoefficient = 1.0 + 0.02 * (temperature - 25.0); //temperature compensation formula: fFinalResult(25^C) = fFinalResult(current)/(1.0+0.02*(fTP-25.0));
    float compensationVolatge = averageVoltage / compensationCoefficient; //temperature compensation
    tdsValue = (133.42 * compensationVolatge * compensationVolatge * compensationVolatge - 255.86 * compensationVolatge * compensationVolatge + 857.39 * compensationVolatge) * 0.5; //convert voltage value to tds value
    //Serial.print("voltage:");
    //Serial.print(averageVoltage,2);
    //Serial.print("V   ");
    //Serial.print("TDS Value:");
    //Serial.print(tdsValue,0);
    //Serial.println("ppm");
  }
}

int getMedianNum(int bArray[], int iFilterLen)  {
  int bTab[iFilterLen];
  for (byte i = 0; i < iFilterLen; i++)
    bTab[i] = bArray[i];
  int i, j, bTemp;
  for (j = 0; j < iFilterLen - 1; j++)
  {
    for (i = 0; i < iFilterLen - j - 1; i++)
    {
      if (bTab[i] > bTab[i + 1])
      {
        bTemp = bTab[i];
        bTab[i] = bTab[i + 1];
        bTab[i + 1] = bTemp;
      }
    }
  }
  if ((iFilterLen & 1) > 0)
    bTemp = bTab[(iFilterLen - 1) / 2];
  else
    bTemp = (bTab[iFilterLen / 2] + bTab[iFilterLen / 2 - 1]) / 2;
  return bTemp;
}

float ph() {
//PH Formula - added here because it didn't want to calculate
    static unsigned long samplingTime = millis();
    static unsigned long printTime = millis();
    static float pHValue, voltage;
    if (millis() - samplingTime > samplingInterval)
    {
      pHArray[pHArrayIndex++] = analogRead(SensorPin);
      if (pHArrayIndex == ArrayLenth)pHArrayIndex = 0;
      voltage = avergearray(pHArray, ArrayLenth) * 5.0 / 1024;
      pHValue = 3.5 * voltage + Offset;
      samplingTime = millis();
      return pHValue;
    }
}

float getTemp() { //Temp Formula
  //returns the temperature from one DS18S20 in DEG Celsius

  byte data[12];
  byte addr[8];

  if ( !ds.search(addr)) {
    //no more sensors on chain, reset search
    ds.reset_search();
    return -1000;
  }

//  if ( OneWire::crc8( addr, 7) != addr[7]) {
//    Serial.println("CRC is not valid!");
//    return -1000;
//  }

//  if ( addr[0] != 0x10 && addr[0] != 0x28) {
//    Serial.print("Device is not recognized");
//    return -1000;
//  }

  ds.reset();
  ds.select(addr);
  ds.write(0x44, 1); // start conversion, with parasite power on at the end

  byte present = ds.reset();
  ds.select(addr);
  ds.write(0xBE); // Read Scratchpad


  for (int i = 0; i < 9; i++) { // we need 9 bytes
    data[i] = ds.read();
  }

  ds.reset_search();

  byte MSB = data[1];
  byte LSB = data[0];

  float tempRead = ((MSB << 8) | LSB); //using two's compliment
  float TemperatureSum = tempRead / 16;

  return TemperatureSum;

}`

**Comment by arkhipenko** [comment]
Let's take this offline from the issues. Please send me an email to arkhipenko@hotmail.com

**Comment by arkhipenko** [comment]
@tstanescu1 : Do you still want the updated code? I have it written just need your email to send it to.
Please send me an email to arkhipenko@hotmail.com

**Comment by tstanescu1** [comment]
Hi, i'm sorry I had to pause my project for a bit. I will send you an email as soon as I start it back up.

Thank you for all your help!
