### ISSUE TITLE
No Task default contructor if _TASK_STATUS_REQUEST

### ISSUE THREAD

**Issue by vadimostanin** [arkhipenko/TaskScheduler#68]
I defined _TASK_STATUS_REQUEST, then I can't create empty Task object, because there is
two constructors that are satisfy conditions with empty arguments:
    INLINE Task(unsigned long aInterval=0, long aIterations=0, TaskCallback aCallback=NULL, Scheduler* aScheduler=NULL, bool aEnable=false, TaskOnEnable aOnEnable=NULL, TaskOnDisable aOnDisable=NULL);

#ifdef _TASK_STATUS_REQUEST
    INLINE Task(TaskCallback aCallback=NULL, Scheduler* aScheduler=NULL, TaskOnEnable aOnEnable=NULL, TaskOnDisable aOnDisable=NULL);

**Comment by arkhipenko** [comment]
Yes, it's a known problem - I just don't have time to fix it.
Workaround: do not use default Task t; constructor. 
Use something like Task t(&callback, &scheduler);

**Comment by vadimostanin** [comment]
Yes, seems acceptable workarounds exists. I will close issue.
