### ISSUE TITLE
Request: pass in the task and the scheduler to the callback function

### ISSUE THREAD

**Issue by patmoore** [arkhipenko/TaskScheduler#7]
this will allow a callback to be used for multiple tasks.

**Comment by arkhipenko** [comment]
Please review the documentation. It is already done.

**Comment by patmoore** [comment]
What documentation?

But more importantly

On line 627:

```
                                if ( iCurrent->iCallback ) {
                                        ( *(iCurrent->iCallback) )();
```
this should be:

```
                                if ( iCurrent->iCallback ) {
                                        ( *(iCurrent->iCallback) )(iCurrent);
```

**Comment by arkhipenko** [comment]
O come on, really? The documentation in the extras folder:

https://github.com/arkhipenko/TaskScheduler/tree/master/extras


The Scheduler class already provides access to currently executing task. 
    inline Task& Scheduler::currentTask() {return *iCurrent; }

Most of the tasks do not need this so I decided not to waste time pushing the reference to stack and back all the time.

Refer to example 7 for usage:

https://github.com/arkhipenko/TaskScheduler/blob/master/examples/Scheduler_example7_WDT/Scheduler_example7_WDT.ino

**Comment by patmoore** [comment]
That location is not a normal place for documentation. 

Maybe you could create the gh-pages branch? see: https://help.github.com/articles/creating-project-pages-manually/

**Comment by arkhipenko** [comment]
For Arduino library they suggest documentation is placed in the extras folder:
\
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#library-metadata
