### ISSUE TITLE
Argument with task

### ISSUE THREAD

**Issue by afagard** [arkhipenko/TaskScheduler#80]
Love the lib, even though it is a bit hard for me to follow some of the examples (so many callbacks).

In any case, I was wondering if there was a way to pass an argument with a task:

e.g.

`Task tUpdateRtc(1UL * 60UL * 1000UL, TASK_FOREVER, &updateRtc(true), &hpr); // every 1 minute
`

**Comment by arkhipenko** [comment]
No easy way to do it with Dynamic Tasks calling static callback methods.
You can use Local Task Storage pointer for this. 
Wiki: [here](https://github.com/arkhipenko/TaskScheduler/wiki/API-Task#local-task-storage-methods-1)
Example: [here ](https://github.com/arkhipenko/TaskScheduler/blob/master/examples/Scheduler_example08_LTS/Scheduler_example08_LTS.ino)
