### ISSUE TITLE
Task schedule inconsistent at start

### ISSUE THREAD

**Issue by alw1746** [arkhipenko/TaskScheduler#9]
Hi Anatoli,

Nice work on the task scheduler! I tested the first example and while it worked very well, the tasks did not follow the actual schedule until the fourth iteration. Attached the monitor result and example code which I modified to display interation count. Any clues? Could it be something odd with serial.println rather than the task itself?

regards,
Alex
[Scheduler_example.txt](https://github.com/arkhipenko/TaskScheduler/files/37729/Scheduler_example.txt)
[monitor.txt](https://github.com/arkhipenko/TaskScheduler/files/37730/monitor.txt)

**Comment by alw1746** [comment]
Forgot to mention I ran it on an Arduino Pro Mini 5V 16Mhz.

**Comment by arkhipenko** [comment]
Please post your modified code here. I think I know what causes it, but want to make sure.





On Wed, Nov 18, 2015 at 2:34 AM -0800, "alw1746" <notifications@github.com> wrote:





Forgot to mention I ran it on an Arduino Pro Mini 5V 16Mhz.

---

**Comment by arkhipenko** [comment]
Sorry, didn't realize code was attached.
This is caused by the delay (5000) statement at the end of setup(). 
Tasks were enabled before. Delay blocks there execution for 5 sec, so first 4 cycles they "catch up". 
Try without delay or enable tasks after delay.

**Comment by arkhipenko** [comment]
Check the most recent example 1 please. This is how it is done there.
