### ISSUE TITLE
unused parameter 'aRecursive'

### ISSUE THREAD

**Issue by FedeBev** [arkhipenko/TaskScheduler#99]
Hi there,
thanks for this amazing work!

Compiling without _TASK_PRIORITY, the following warning is thrown (with strict build):
```
/libraries/TaskScheduler/src/TaskScheduler.h:850:32: warning: unused parameter 'aRecursive' [-Wunused-parameter]
 void Scheduler::startNow( bool aRecursive ) {
```
I would just use a preprocessor condition here
https://github.com/arkhipenko/TaskScheduler/blob/2470286e0ba3f21768c881e7e23dd2f2ac85674f/src/TaskScheduler.h#L805

as few lines below
https://github.com/arkhipenko/TaskScheduler/blob/2470286e0ba3f21768c881e7e23dd2f2ac85674f/src/TaskScheduler.h#L812-L814

**Comment by arkhipenko** [comment]
Pushed fix to the **testing** branch - please test if you have time.
